version: '3.3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - oander
  api:
    restart: always
    build: .
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    networks:
      - oander
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=rediss
      - API_PORT=3000
networks:
  oander:
    driver: bridge
